[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn wsgi:application"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[[services]]
name = "ai-rfx-backend"

[services.variables]
ENVIRONMENT = "production"
PORT = "8000"
